#!/usr/bin/python3
import sys
from math import sqrt
from math import gcd

def rho_fun(n):
    if n % 2 == 0:
        return 2
    x = 2; y = 2; d = 1
    f = lambda x: (x**2 + 1) % n
    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x-y), n)
    return d

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)
try:
    with open(sys.argv[1], 'r') as file:
        for line in file:
            number = int(line)
            check = 0
            '''
            for i in range(2, int(sqrt(sqrt(number))) + 1):
                if number % i == 0:
                    print("{}={}*{}".format(int(number), int(number//i), int(i)))
                    check = 1
                    break
            if check == 0:
                for i in range(number - 1, int(number - int(sqrt(number))) + 1, -1):
                    if number % i == 0:
                        print("{}={}*{}".format(int(number),int(i), int(number//i)))
                        check = 1
                        break
                    '''
            if check == 0:
                print("{}={}*{}".format(number, number // rho_fun(number), rho_fun(number)))
except IOError:
    print("Can't read the file")
    sys.exit(1)
