#!/usr/bin/python3
import sys
import random
from math import sqrt
from math import gcd


def rho_fun(n):
    if n % 2 == 0:
        return 2
    x, y, d = 2, 2, 1
    f = (lambda x: (x**2 + 1) % n)
    while d == 1 and not is_prime(d):
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x-y), n)
    return d


def is_prime(n):
   if n <= 1:
       return False
   if n <= 3:
       return True
   if n % 2 == 0 or n % 3 == 0:
       return False
   i = 5
   while i * i <= n:
       if n % i == 0 or n % (i + 2) == 0:
           return False
       i += 6
   return True


if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)
try:
    with open(sys.argv[1], 'r') as file:
        for line in file:
            number = int(line)
            n = rho_fun(number)
            if n < number // n:
                print("{}={}*{}".format(number, number // n, n))
            else:
                print("{}={}*{}".format(number, n, number // n))
except IOError:
    print("Can't read the file")
    sys.exit(1)
